# Dependencies
markdown:         redcarpet
highlighter:         true

# Permalinks
permalink:        pretty

# Setup
title:            Joan Romano
tagline:          
url:              http://joanromano.github.io/
paginate:         1
baseurl:          /
author:
  name:           Joan Romano
  url:            https://twitter.com/joanromano

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/joanromano/joanromano.github.io

# This is the list of pages to include in the header of the website.
pages_list:       
  About: '/about/'